site_name: quafel
theme:
  name: material
  highlightjs: true
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: ["src"]
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - toc:
        permalink: "#"
        baselevel: 1
        separator: "_"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Melvin-Strobl
      name: Researchgate
    - icon: fontawesome/brands/github
      link: https://github.com/stroblme/qLearning
      name: Github
    - icon: fontawesome/solid/section
      link: https://stroblme.de/index.php/legal-notice/
      name: Legal Notice