name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev
    - name: Test with pytest
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report -m
        poetry run coverage html
    - name: Share coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/